services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  python-service:
    container_name: python_service
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  golang-service:
    container_name: golang_service
    build:
      context: ./golang-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001" 

volumes:
  grafana-storage: