global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'python-service'
    static_configs:
      - targets: ['python-service:3000']

  - job_name: 'golang-service'
    static_configs:
      - targets: ['golang-service:3001']
